# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for RedSocks2
LUCI_DEPENDS:=+redsocks2
LUCI_PKGARCH:=all

include ../../../../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
